# Generated by Django 6.0 on 2025-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuperstoreDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="Order Date")),
                ("ship_date", models.DateField(verbose_name="Ship Date")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("South", "South"),
                            ("West", "West"),
                            ("Central", "Central"),
                            ("East", "East"),
                        ],
                        max_length=10,
                        verbose_name="Region",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Kentucky", "Kentucky"),
                            ("California", "California"),
                            ("Florida", "Florida"),
                            ("North Carolina", "North Carolina"),
                            ("Washington", "Washington"),
                            ("Texas", "Texas"),
                            ("Wisconsin", "Wisconsin"),
                            ("Utah", "Utah"),
                            ("Nebraska", "Nebraska"),
                            ("Pennsylvania", "Pennsylvania"),
                            ("Illinois", "Illinois"),
                            ("Minnesota", "Minnesota"),
                            ("Michigan", "Michigan"),
                            ("Delaware", "Delaware"),
                            ("Indiana", "Indiana"),
                            ("New York", "New York"),
                            ("Arizona", "Arizona"),
                            ("Virginia", "Virginia"),
                            ("Tennessee", "Tennessee"),
                            ("Alabama", "Alabama"),
                            ("South Carolina", "South Carolina"),
                            ("Oregon", "Oregon"),
                            ("Colorado", "Colorado"),
                            ("Iowa", "Iowa"),
                            ("Ohio", "Ohio"),
                            ("Missouri", "Missouri"),
                            ("Oklahoma", "Oklahoma"),
                            ("New Mexico", "New Mexico"),
                            ("Louisiana", "Louisiana"),
                            ("Connecticut", "Connecticut"),
                            ("New Jersey", "New Jersey"),
                            ("Massachusetts", "Massachusetts"),
                            ("Georgia", "Georgia"),
                            ("Nevada", "Nevada"),
                            ("Rhode Island", "Rhode Island"),
                            ("Mississippi", "Mississippi"),
                            ("Arkansas", "Arkansas"),
                            ("Montana", "Montana"),
                            ("New Hampshire", "New Hampshire"),
                            ("Maryland", "Maryland"),
                            ("District of Columbia", "District of Columbia"),
                            ("Kansas", "Kansas"),
                            ("Vermont", "Vermont"),
                            ("Maine", "Maine"),
                            ("South Dakota", "South Dakota"),
                            ("Idaho", "Idaho"),
                            ("North Dakota", "North Dakota"),
                            ("Wyoming", "Wyoming"),
                            ("West Virginia", "West Virginia"),
                        ],
                        max_length=50,
                        verbose_name="State",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("Consumer", "Consumer"),
                            ("Corporate", "Corporate"),
                            ("Home Office", "Home Office"),
                        ],
                        max_length=20,
                        verbose_name="Segment",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Furniture", "Furniture"),
                            ("Office Supplies", "Office Supplies"),
                            ("Technology", "Technology"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        choices=[
                            ("Bookcases", "Bookcases"),
                            ("Chairs", "Chairs"),
                            ("Labels", "Labels"),
                            ("Tables", "Tables"),
                            ("Storage", "Storage"),
                            ("Furnishings", "Furnishings"),
                            ("Art", "Art"),
                            ("Phones", "Phones"),
                            ("Binders", "Binders"),
                            ("Appliances", "Appliances"),
                            ("Paper", "Paper"),
                            ("Accessories", "Accessories"),
                            ("Envelopes", "Envelopes"),
                            ("Fasteners", "Fasteners"),
                            ("Supplies", "Supplies"),
                            ("Machines", "Machines"),
                            ("Copiers", "Copiers"),
                        ],
                        max_length=30,
                        verbose_name="Sub Category",
                    ),
                ),
                (
                    "ship_mode",
                    models.CharField(
                        choices=[
                            ("Second Class", "Second Class"),
                            ("Standard Class", "Standard Class"),
                            ("First Class", "First Class"),
                            ("Same Day", "Same Day"),
                        ],
                        max_length=20,
                        verbose_name="Ship Mode",
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Sales"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Profit"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Discount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Superstore Dashboard",
                "verbose_name_plural": "Superstore Dashboards",
                "ordering": ["-order_date"],
            },
        ),
    ]
